name: queue
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mocktail: ^0.3.0
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  provider: ^6.0.2
  flutter_triple: ^1.2.7+2
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  fake_cloud_firestore: ^1.2.2
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
