// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DCMJPi9kcu0o2pV_Vw9QcBESlXlcAEQ',
    appId: '1:383489200455:web:bd3491fc72cf73c716bc62',
    messagingSenderId: '383489200455',
    projectId: 'queue-management-50541',
    authDomain: 'queue-management-50541.firebaseapp.com',
    storageBucket: 'queue-management-50541.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7obsHl2q5lTTR4vHV7NioaO0lolNJHSc',
    appId: '1:383489200455:android:21c0d54248782cff16bc62',
    messagingSenderId: '383489200455',
    projectId: 'queue-management-50541',
    storageBucket: 'queue-management-50541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDVyfsuYtJ_f1FheidVdKOYvUu-NQF94',
    appId: '1:383489200455:ios:c64540e60812212016bc62',
    messagingSenderId: '383489200455',
    projectId: 'queue-management-50541',
    storageBucket: 'queue-management-50541.appspot.com',
    iosClientId:
        '383489200455-nu0mjm4sf9b6laqse1ch0j5141tupbra.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
}
